server:
  port: 8080
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: survey
    password: kdh
    driver-class-name: oracle.jdbc.driver.OracleDriver
mybatis:
  mapper-locations: classpath*:/mybatis/mapper/**/*.xml


